#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Installs host-relay.cjs and the entrypoint that starts it.
#
# Why an entrypoint and not postStartCommand: the CLI runs lifecycle hooks in a
# `docker exec` and tears down everything that exec leaves behind — a
# backgrounded daemon does not survive it, even detached with `setsid`. Feature
# entrypoints run in the container's main process chain instead, which is how
# docker-in-docker keeps dockerd alive.
# ---------------------------------------------------------------------------
set -euo pipefail

PORTS="${PORTS:-8080,3000,5000,5003,4318}"
TARGET="${TARGET:-host.docker.internal}"

FEATURE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RELAY_SCRIPT="/usr/local/share/host-relay.cjs"
INIT_SCRIPT="/usr/local/share/host-relay-init.sh"

# Resolve node now: the entrypoint runs before any profile is sourced, so it
# cannot rely on PATH looking the way an interactive shell does.
NODE_BIN="$(command -v node || echo /usr/bin/node)"

install -m 0755 "${FEATURE_DIR}/host-relay.cjs" "${RELAY_SCRIPT}"

cat > "${INIT_SCRIPT}" <<EOF
#!/bin/sh
# Starts the host relay once per container start. Generated by the host-relay
# dev container feature — edit the feature, not this file.
#
# The log lives in /var/log, not /tmp: docker-in-docker mounts a tmpfs over
# /tmp partway through the entrypoint chain, which would hide the file from
# everyone except the already-running relay.
RELAY_LOG=/var/log/host-relay.log

if ! pgrep -f '[h]ost-relay.cjs' >/dev/null 2>&1; then
  HOST_RELAY_PORTS="\${HOST_RELAY_PORTS:-${PORTS}}" \\
  HOST_RELAY_TARGET="\${HOST_RELAY_TARGET:-${TARGET}}" \\
    "${NODE_BIN}" "${RELAY_SCRIPT}" > "\${RELAY_LOG}" 2>&1 &
fi
EOF

chmod 0755 "${INIT_SCRIPT}"

echo "host-relay installed: ${PORTS} -> ${TARGET} (entrypoint ${INIT_SCRIPT})"
