name: E2E (existing environment)

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: read
  checks: write

jobs:
  e2e:
    uses: ianoflynnautomation/bjjeire-ci-templates/.github/workflows/playwright-tests.yml@main
    with:
      app-env: staging
      base-url: https://staging.example.com
      api-url: https://api.staging.example.com
      test-tags: '@acceptance'
      shard-total: 4
      playwright-projects: |
        api
        chromium-desktop
        firefox-desktop
        webkit-desktop
        snapshots
        a11y
        mobile-iphone
      project-shard-overrides: |
        api=2
        chromium-desktop=8
        firefox-desktop=2
        webkit-desktop=2
        snapshots=2
        a11y=2
        mobile-iphone=2
      test-repo: ianoflynnautomation/bjjeire-tests
      fail-on-flaky: true
    secrets: inherit
